name: deploy site

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      -name: checkout repo
      uses: actions/checkout@v3
      with:
        token: ${{ steps.deployment.output.page_url }}

      - name: compile and generate the files
        run: mkdocs build

      - name: init new repo in site/ and add all files
        run: |
          cd site/
          git init
          git add -A
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Action"
          git commit -m "Deploy"

      - name: force push to destination branch
        run: |
          git push -f https://github.com/NarayanPradhan-Dev/mkdocs-gha-learn.git main:gh-pages
